server:
  port: 8085

spring:
  application:
    name: scanner
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scannerdb
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true