server:
  port: 8085

spring:
  application:
    name: scanner
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true