version: "3.8"

services:
  nginx-react:
    image: scanner-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: scannerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: 'redis-latest'
    ports:
      - "6379:6379"

  app:
    image: scanner-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: 86dc1443b4e0c83dcda17c4e4635c16517bac495e5cb7675eefcb650222fc70e7f697b5d5c75992ff9e2c4ecc5092121e3990e8abdf3879337c8195a27f986cfc1390319cb67dcc24f88e643e78a999e8d2b6fa8a9dde995ebf5b122ca999b3f673dddf4a00f20e73c23e90f8c19f4ca34655ff4e507ed2fe4af4f6f93b36a2c97866540409af95227d8a20ee302ed050a15a061105d8df94bbe04921624fe07d859272c69394fecaa00e4f76784b25e33ebd6afd9a24b7e80e8dc3932e3c67cc5d2e6107359f63fd0abf9387484eac455905b84d8d0307e93cc16bdb3338ff8fb5fd043f5d365139f7c9533a60039248ebf1024cdbf64bab78bd90838f007d3
      JWT_LIFETIME: 360m
      JWT_REFRESHTOKENLIFETIME: 720m
      SPRING_DATA_REDIS_HOST: localhost
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_APPLICATION_NAME: scanner
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/scannerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: false
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_OPEN-IN-VIEW: true
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always
      EXCHANGES_APIKEYS_GATEIO_KEY: 772206b7012c7e1032e2bcb6d206716d
      EXCHANGES_APIKEYS_GATEIO_SECRET: ac5066ea5bed73af02bd53ad998045d879e2a93c0ae4b33dd6c339d4057c6d02
      EXCHANGES_APIKEYS_MEXC_KEY: mx0vglPGU3h0E9HsH9
      EXCHANGES_APIKEYS_MEXC_SECRET: 9db3c31ec9ec4ff5bef23a4e4c73b8bd
      EXCHANGES_APIKEYS_KUCOIN_KEY: 6682ea71c3ea0f0001512c6c
      EXCHANGES_APIKEYS_KUCOIN_SECRET: 79d4417f-f6ae-43e5-a07f-77ce2555a2ce
      EXCHANGES_APIKEYS_KUCOIN_PASSPHRASE: passphrase
      EXCHANGES_APIKEYS_BYBIT_KEY: jF9vCKenFLZVvoUnIM
      EXCHANGES_APIKEYS_BYBIT_SECRET: YXzD07o4fFFQqaSafzFWGnoZ0fdoGCuoO2qD
      EXCHANGES_APIKEYS_HUOBI_KEY: 822a8341-e3fa1297-bgbfh5tv3f-8e510
      EXCHANGES_APIKEYS_HUOBI_SECRET: 4fe780a3-fe999617-6cac79b9-9c040
      EXCHANGES_APIKEYS_POLONIEX_KEY: F7GHAMP0-7N2BC4PM-DKG7XJKG-4MUTCIL2
      EXCHANGES_APIKEYS_POLONIEX_SECRET: 511c555da114daf6d0353f802df31b6f817eeb28fa4765c1f5c557d46c70f15882bdf2a55e86de0284bf0e175e550d5c66d66d357933442ff48cdd7f33fd1448
      EXCHANGES_APIKEYS_OKX_KEY: 4f817d5b-5ced-4b00-b5e3-d9c3bf7a0e70
      EXCHANGES_APIKEYS_OKX_SECRET: 03EC605D55CF9D8B7E405BD1AB258B43
      EXCHANGES_APIKEYS_OKX_PASSPHRASE: Passphrase1#
      EXCHANGES_APIKEYS_BITMART_KEY: 19396aef3a650f3995c5caad42935bcc681a0cff
      EXCHANGES_APIKEYS_BITMART_SECRET: 708117f5f899122b305787f394897b5a88a4459c7e48d4e3dbf2e066144fa16c
      EXCHANGES_APIKEYS_BITMART_MEMO: scanner
      EXCHANGES_APIKEYS_LBANK_KEY: 0a1b7b74-eb2f-4cce-8900-b6980ea40df7
      EXCHANGES_APIKEYS_LBANK_SECRET: 009554932EFC398E2A63C9E8E1737852
      EXCHANGES_APIKEYS_COINEX_KEY: 7323B954D3EF4A61A86B1F1B843538D4
      EXCHANGES_APIKEYS_COINEX_SECRET: B34DC3F4376AA64345CD0EC811391A599D2A60C01FF954EB
      EXCHANGES_APIKEYS_XT_KEY: 21f4f1a6-7d48-4a08-b712-6993d4262bc5
      EXCHANGES_APIKEYS_XT_SECRET: 10db7f81923dc256b4de9738de75626d1e436574
      EXCHANGES_APIKEYS_BINGX_KEY: oDp2jGhexStzRCZ3pYiFZ2WCjb0UtITZCoVf03TPXWufuMYNWC3PILjJUU5nCq1nIQUykg7Sf0DWUnUhlF7lg
      EXCHANGES_APIKEYS_BINGX_SECRET: mYHNvDKq1Md7gyKwR0aRsS07uA8gCnKN3QDloQlYyEwqSLnXwmIrqvofxMh9aHgc0LVXN1B2qAFhJDR4g
      EXCHANGES_APIKEYS_BINANCE_KEY: OcVdL4HyRH28bHrxaFPjCX0UI99oh1CdBSQXUXq7zK0qztXz9luimU9sMmxIIYOY
      EXCHANGES_APIKEYS_BINANCE_SECRET: 2jjX7IB3QQvsmZcxf9kBWFSAKvD1l0CHMvUO3PqXJmW70DTnNZ7DYcRyk133mV9l
      COINMARKETCAP_APIKEY: 0e3f75dc-96af-4ae9-8ffc-d0c1876254f5

    depends_on:
      - postgres, redis

volumes:
  postgres_data: