version: '3.8'
services:
  postgres:
    image: postgres:16.2
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=scannerdb
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"